apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-git
spec:
  selector:
    matchLabels:
      app: argocd-git
  replicas: 2
  template:
    metadata:
      labels:
        app: argocd-git
    spec:
      containers:
        - name: argocd-git
          image: jerrybaijy/student-springboot-react-frontend:v1.0
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
              ephemeral-storage: "1Gi"
            limits:
              memory: "1Gi"
              cpu: "500m"
              ephemeral-storage: "1Gi"